spring.application.name=kindergarten-service

spring.datasource.hikari.connectionTimeout=20000
spring.datasource.hikari.maximumPoolSize=5

spring.datasource.url=jdbc:postgresql://localhost:5432/empdb
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=create-drop

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

token.signing.key=pasSFSSAsword1sdjsfsbjbfASSDds12141=SADdfs214

server.port = 8080

spring.jpa.show-sql=true
